apiVersion: v1
kind: Service
metadata:
  name: profile-app
  namespace: liveproject
  labels:
    app: profile
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: profile
    tier: service
