apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: profile
  name: profile
  namespace: liveproject
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: profile
      tier: service
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: profile
        tier: service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://profile-mysql:3306/profiles
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        image: grafpoo/profile-app
        imagePullPolicy: Always
        name: profile
        ports:
        - containerPort: 8080
          name: profile
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home
          name: profile-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: profile-persistent-storage
        persistentVolumeClaim:
          claimName: profile-pv-claim
